// Textos de todo el sitio en español. Traducir solo los valores, nunca las claves.
export default {
  site: {
    title: 'Guía visual de urología pediátrica',
    tagline: 'Modelos interactivos para ayudar a las familias a entender la condición de su hijo o hija y las opciones de tratamiento.',
    disclaimer:
      'Para educación durante una visita con el equipo médico de su hijo o hija. Esta guía no reemplaza el consejo médico para su hijo o hija.',
    author: 'Creado por Andrew T. Gabrielson, MD',
  },
  nav: {
    home: 'Todas las condiciones',
    present: 'Presentar',
    exitPresent: 'Salir',
    draw: 'Dibujar',
    clear: 'Borrar',
    share: 'Compartir',
    print: 'Imprimir',
    prev: 'Atrás',
    next: 'Siguiente',
    close: 'Cerrar',
    comingSoon: 'Próximamente',
    language: 'Idioma',
    notTranslated: 'Este capítulo todavía no está traducido, por eso se muestra en inglés.',
  },
  player: { back: 'Atrás', next: 'Siguiente', play: 'Reproducir todo' },
  share: {
    title: 'Vuelva a verlo en casa',
    body: 'Escanee con la cámara de su teléfono para abrir esta página.',
  },
  sections: {
    embryology: 'Cómo se forma',
    pathology: 'Qué está pasando',
    treatment: 'Opciones de tratamiento',
    takeaways: 'Puntos clave',
  },
  labels: {
    kidney: 'Riñón',
    ureter: 'Uréter',
    bladder: 'Vejiga',
    urethra: 'Uretra',
  },
  groups: {
    upper: 'Riñón y vías urinarias altas',
    lower: 'Vejiga y vías urinarias bajas',
    genital: 'Condiciones genitales y del escroto',
  },
  conditions: {
    hydronephrosis: 'Hidronefrosis',
    vur: 'Reflujo vesicoureteral (RVU)',
    upj: 'Obstrucción de la unión pieloureteral',
    uvj: 'Obstrucción ureterovesical / megauréter',
    mcdk: 'Riñón displásico multiquístico',
    duplex: 'Riñón duplicado',
    ectopic: 'Uréter ectópico / ureterocele',
    stones: 'Piedras en el riñón, uréter y vejiga',
    pkd: 'Enfermedad renal poliquística',
    uti: 'Infección urinaria',
    enuresis: 'Mojar la cama',
    bbd: 'Escapes de orina durante el día',
    neurogenic: 'Vejiga neurogénica',
    bowel: 'Disfunción de vejiga e intestino',
    puv: 'Válvulas uretrales posteriores',
    exstrophy: 'Extrofia vesical y epispadias',
    hypospadias: 'Hipospadias',
    cryptorchidism: 'Testículo no descendido',
    hydrocele: 'Hidrocele',
    hernia: 'Hernia inguinal',
    torsion: 'Torsión testicular',
    varicocele: 'Varicocele',
    phimosis: 'Fimosis y parafimosis',
    meatal: 'Estenosis del meato',
    labial: 'Adherencias de labios vulvares',
    dsd: 'DSD / HSC',
  },
  blurbs: {
    hydronephrosis: 'Hinchazón de la parte del riñón que recoge la orina.',
    vur: 'La orina regresa de la vejiga hacia el riñón.',
    upj: 'Un estrechamiento donde el riñón se une al uréter.',
    uvj: 'Un estrechamiento donde el uréter se une a la vejiga.',
    duplex: 'Un riñón con dos sistemas de drenaje en lugar de uno.',
    ectopic: 'Un uréter que desemboca en el lugar equivocado, o una bolsa como globo en su extremo.',
    torsion: 'Una emergencia: el testículo se tuerce y pierde su riego de sangre.',
    cryptorchidism: 'Un testículo que no terminó de bajar al escroto.',
    hydrocele: 'Líquido alrededor del testículo que hincha el escroto.',
    hernia: 'El intestino se desliza hacia la ingle o el escroto por una bolsa abierta.',
    varicocele: 'Venas hinchadas encima del testículo, casi siempre del lado izquierdo.',
    phimosis: 'Un prepucio apretado, o uno atorado detrás de la cabeza del pene.',
    meatal: 'Una abertura estrecha en la punta del pene.',
    labial: 'Los labios internos de la vulva se pegan entre sí.',
    uti: 'Una infección de la vejiga o del riñón.',
    stones: 'Depósitos duros de minerales en el riñón, el uréter o la vejiga.',
    hypospadias: 'El orificio para orinar está debajo del pene en lugar de en la punta.',
    enuresis: 'Mojar la cama al dormir después de los 5 años.',
    bbd: 'Accidentes durante el día, urgencia y hábitos de vejiga o intestino.',
    neurogenic: 'Una vejiga afectada por problemas de los nervios, como la espina bífida.',
    bowel: 'Cómo el estreñimiento y aguantar el excremento afectan la vejiga.',
    puv: 'Pliegues de tejido de más en la uretra de un niño que bloquean la orina.',
  },
};
