// Site-wide wording. To translate, copy this folder (e.g. content/es/) and
// translate the values — never the keys.
export default {
  site: {
    title: 'Pediatric Urology Visual Guide',
    tagline: 'Interactive models to help families understand their child’s condition and treatment choices.',
    disclaimer:
      'For education during a visit with your child’s care team. This guide does not replace medical advice for your child.',
  },
  nav: {
    home: 'All conditions',
    present: 'Present',
    exitPresent: 'Exit',
    draw: 'Draw',
    clear: 'Clear',
    share: 'Share',
    print: 'Print',
    prev: 'Back',
    next: 'Next',
    close: 'Close',
    comingSoon: 'Coming soon',
  },
  share: {
    title: 'Look at this again at home',
    body: 'Scan with your phone camera to open this page.',
  },
  sections: {
    embryology: 'How it forms',
    pathology: 'What’s happening',
    treatment: 'Treatment options',
    takeaways: 'Key points',
  },
  labels: {
    kidney: 'Kidney',
    ureter: 'Ureter',
    bladder: 'Bladder',
    urethra: 'Urethra',
  },
  groups: {
    upper: 'Kidney and upper urinary tract',
    lower: 'Bladder and lower urinary tract',
    genital: 'Genital and scrotal conditions',
  },
  conditions: {
    hydronephrosis: 'Hydronephrosis',
    vur: 'Vesicoureteral reflux (VUR)',
    upj: 'UPJ obstruction',
    uvj: 'UVJ obstruction / megaureter',
    mcdk: 'Multicystic dysplastic kidney',
    duplex: 'Duplicated kidney',
    ectopic: 'Ectopic ureter / ureterocele',
    stones: 'Kidney stones',
    pkd: 'Polycystic kidney disease',
    uti: 'Urinary tract infection',
    enuresis: 'Bedwetting',
    bbd: 'Daytime wetting & voiding dysfunction',
    neurogenic: 'Neurogenic bladder',
    puv: 'Posterior urethral valves',
    exstrophy: 'Bladder exstrophy',
    hypospadias: 'Hypospadias / epispadias',
    bladderStones: 'Bladder stones',
    cryptorchidism: 'Undescended testicle',
    hydrocele: 'Hydrocele',
    hernia: 'Inguinal hernia',
    torsion: 'Testicular torsion',
    varicocele: 'Varicocele',
    phimosis: 'Phimosis & paraphimosis',
    meatal: 'Meatal stenosis',
    labial: 'Labial adhesions',
    dsd: 'DSD / CAH',
  },
  blurbs: {
    hydronephrosis: 'Swelling of the part of the kidney that collects urine.',
    vur: 'Urine flows backward from the bladder toward the kidney.',
    upj: 'A narrow spot where the kidney meets the ureter.',
    uvj: 'A narrow spot where the ureter meets the bladder.',
    duplex: 'A kidney with two drainage systems instead of one.',
    ectopic: 'A ureter that opens in the wrong place, or a balloon-like pouch at its end.',
    torsion: 'An emergency: the testicle twists and loses its blood supply.',
    cryptorchidism: 'A testicle that did not finish moving down into the scrotum.',
    puv: 'Extra flaps of tissue in a boy’s urethra that block urine.',
  },
};
